[workspace]

members = [
  "crates/core",
  "crates/napi",
  "crates/wasm"
]

[profile.dev.package.swc_css_prefixer]
opt-level = 2

# This is a workaround for wasm timeout issue
[profile.dev.package."*"]
debug-assertions = false

[profile.release]
lto = true
