[workspace]

members = [
  "crates/core",
  "crates/napi",
  "crates/wasm"
]

[profile.dev.package.swc_css_prefixer]
opt-level = 2

# This is a workaround for wasm timeout issue
[profile.dev.package."*"]
debug-assertions = false

[profile.release]
lto = true

# Declare dependencies used across workspace packages requires single version bump.
# ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
[workspace.dependencies]
swc_core = "0.28.10"