[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST transforms for styled-jsx"
edition = "2018"
license = "Apache-2.0"
name = "styled_jsx"
repository = "https://github.com/vercel/next.js.git"
version = "0.20.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-error = "1.0.0"
tracing = "0.1.32"

swc_core = { version = "0.28.4", features = [
  "common",
  "css_ast",
  "css_codegen",
  "css_parser",
  "css_prefixer",
  "css_visit",
  "ecma_parser",
  "ecma_minifier",
  "ecma_utils",
  "ecma_visit"
] }

[dev-dependencies]
testing = "0.31.3"
swc_core = { version = "0.28.4", features = [
  "testing_transform"
] }
