[package]
edition = "2018"
name = "next-swc"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.13"
byteorder = "1"
chrono = "0.4"
easy-error = "1.0.0"
either = "1"
fxhash = "0.2.1"
once_cell = "1.8.0"
pathdiff = "0.2.0"
radix_fmt = "1"
regex = "1.5"
serde = "1"
serde_json = "1"
styled_components = "0.19.0"
swc = "0.150.1"
swc_atoms = "0.2.9"
swc_common = {version = "0.17.15", features = ["concurrent", "sourcemap"]}
swc_css = "0.100.0"
swc_ecma_loader = {version = "0.29.0", features = ["node", "lru"]}
swc_ecmascript = {version = "0.132.0", features = ["codegen", "minifier", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"]}
swc_node_base = "0.5.1"
swc_stylis = "0.96.1"
swc_cached = "0.1.1"
tracing = {version = "0.1.28", features = ["release_max_level_off"]}
handlebars = "4.2.1"

[dev-dependencies]
swc_ecma_transforms_testing = "0.69.0"
testing = "0.18.1"
walkdir = "2.3.2"
