on:
  push:
    branches: [canary]
    paths-ignore:
      - 'bench/**'
      - 'docs/**'
      - 'errors/**'
      - 'examples/**'

name: Test macOS

jobs:
  testMacOS:
    name: macOS (Basic, Production, Acceptance)
    runs-on: macos-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_TEST_JOB: 1
      HEADLESS: true

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files || yarn install --frozen-lockfile --check-files
      - run: npm i -g playwright-chromium@1.14.1 && npx playwright install-deps
      - run: node run-tests.js test/development/acceptance/{ReactRefresh,ReactRefreshLogBox-app-doc,ReactRefreshLogBox-scss,ReactRefreshLogBox,ReactRefreshLogBoxMisc,ReactRefreshRegression,ReactRefreshRequire}.test.ts test/development/basic/*.test.ts test/integration/production/test/index.test.js
