name: Validate issue
on:
  issues:
    types: [labeled]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/issue-validator/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
