name: Validate issue
on:
  issues:
    types: [opened, labeled]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/issue-validator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
