[package]
edition = "2018"
name = "next-swc-napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
backtrace = "0.3"
fxhash = "0.2.1"
napi = {version = "1", features = ["serde-json"]}
napi-derive = "1"
next-swc = {version = "0.0.0", path = "../core"}
once_cell = "1.8.0"
serde = "1"
serde_json = "1"
swc = "0.150.1"
swc_atoms = "0.2.9"
swc_bundler = {version = "0.122.0", features = ["concurrent"]}
swc_common = {version = "0.17.15", features = ["concurrent", "sourcemap"]}
swc_ecma_loader = {version = "0.29.0", features = ["node", "lru"]}
swc_ecmascript = {version = "0.132.0", features = ["codegen", "minifier", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"]}
swc_node_base = "0.5.1"

[build-dependencies]
napi-build = "1"
